// <auto-generated />
using System;
using DroneSlam.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DroneSlam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DroneSlamDbContext))]
    partial class DroneSlamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DroneSlam.Domain.Entities.MapAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AbsolutePath")
                        .IsRequired()
                        .HasMaxLength(1400)
                        .HasColumnType("nvarchar(1400)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<bool>("ExistsOnDisk")
                        .HasColumnType("bit");

                    b.Property<Guid>("MapRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MapRunId", "AssetType")
                        .IsUnique();

                    b.ToTable("MapAssets");
                });

            modelBuilder.Entity("DroneSlam.Domain.Entities.MapMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("CoveragePercent")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<long?>("DatabaseSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("LinkCount")
                        .HasColumnType("int");

                    b.Property<Guid>("MapRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("MeshSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("PointCloudSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("PoseCount")
                        .HasColumnType("int");

                    b.Property<long?>("RawPointCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("VoxelPointCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MapRunId")
                        .IsUnique();

                    b.ToTable("MapMetrics");
                });

            modelBuilder.Entity("DroneSlam.Domain.Entities.MapNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MapRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.HasIndex("MapRunId");

                    b.ToTable("MapNotes");
                });

            modelBuilder.Entity("DroneSlam.Domain.Entities.MapRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AbsoluteRunPath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("FlightStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MapKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RelativeRunPath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.HasKey("Id");

                    b.HasIndex("MapKey")
                        .IsUnique();

                    b.ToTable("MapRuns");
                });

            modelBuilder.Entity("DroneSlam.Domain.Entities.MapAsset", b =>
                {
                    b.HasOne("DroneSlam.Domain.Entities.MapRun", "MapRun")
                        .WithMany("Assets")
                        .HasForeignKey("MapRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapRun");
                });

            modelBuilder.Entity("DroneSlam.Domain.Entities.MapMetric", b =>
                {
                    b.HasOne("DroneSlam.Domain.Entities.MapRun", "MapRun")
                        .WithOne("Metric")
                        .HasForeignKey("DroneSlam.Domain.Entities.MapMetric", "MapRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapRun");
                });

            modelBuilder.Entity("DroneSlam.Domain.Entities.MapNote", b =>
                {
                    b.HasOne("DroneSlam.Domain.Entities.MapRun", "MapRun")
                        .WithMany("Notes")
                        .HasForeignKey("MapRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MapRun");
                });

            modelBuilder.Entity("DroneSlam.Domain.Entities.MapRun", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Metric");

                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
